import { notFound } from 'next/navigation';
import { getTenantContext } from '../../../lib/tenant';
import { withTenantDb } from '../../../lib/objects';

export const dynamic = 'force-dynamic';

const fmt = (v: string | number) =>
  Number(v).toLocaleString(undefined, { minimumFractionDigits: 2 });

/** Printable payslip (browser print → PDF). Editorial, ink-friendly. */
export default async function PayslipPage(ctx0: { params: Promise<{ id: string }> }) {
  const { id } = await ctx0.params;
  const ctx = await getTenantContext();
  if (!ctx) notFound();
  const slip = await withTenantDb(async (db) => {
    const [row] = await db<
      { period: string; run_status: string; full_name: string; employee_number: string;
        designation: string | null; department: string | null; epf_number: string | null;
        basic: string; allowances: Record<string, number>; gross: string;
        no_pay_days: string; no_pay_deduction: string; epf_employee: string;
        epf_employer: string; etf_employer: string; apit: string; net: string }[]
    >`select r.period, r.status as run_status, e.full_name, e.employee_number,
        e.designation, e.department, e.epf_number,
        p.basic, p.allowances, p.gross, p.no_pay_days, p.no_pay_deduction,
        p.epf_employee, p.epf_employer, p.etf_employer, p.apit, p.net
      from payslips p
      join payroll_runs r on r.id = p.run_id
      join employees e on e.id = p.employee_id
      where p.id = ${id}`;
    return row ?? null;
  });
  if (!slip) notFound();
  const displayName = (ctx as { displayName?: string }).displayName ?? ctx.slug;
  const allowances = Object.entries(slip.allowances ?? {});

  const Row = ({ l, v, strong = false, neg = false }: { l: string; v: string; strong?: boolean; neg?: boolean }) => (
    <div className={`flex justify-between px-5 py-2.5 border-b border-line last:border-b-0 font-body text-sm ${strong ? 'font-bold text-chalk bg-surface' : 'text-mute-1'}`}>
      <span>{l}</span>
      <span className={neg ? 'text-red-600' : ''}>{neg ? `(${v})` : v}</span>
    </div>
  );

  return (
    <main className="min-h-svh bg-ink py-12 print:py-0">
      <div className="max-w-2xl mx-auto border border-line print:border-0">
        <header className="px-6 py-6 border-b-2 border-chalk flex items-baseline justify-between">
          <div>
            <div className="font-display text-3xl text-chalk tracking-wide">{displayName.toUpperCase()}</div>
            <div className="font-body text-xs text-mute-2 mt-1">
              Payslip · {slip.period} · run {slip.run_status}
            </div>
          </div>
          <div className="font-heading italic text-mute-2 text-sm">Private &amp; confidential</div>
        </header>
        <div className="px-6 py-4 border-b border-line grid grid-cols-2 gap-2 font-body text-sm">
          <div><span className="text-mute-3">Employee</span><br /><b>{slip.full_name}</b> · {slip.employee_number}</div>
          <div><span className="text-mute-3">EPF №</span><br />{slip.epf_number ?? '—'}</div>
          <div><span className="text-mute-3">Designation</span><br />{slip.designation ?? '—'}</div>
          <div><span className="text-mute-3">Department</span><br />{slip.department ?? '—'}</div>
        </div>

        <p className="px-5 pt-5 pb-2 font-body text-xs tracking-widest3 text-brand uppercase">Earnings</p>
        <Row l="Basic salary" v={fmt(slip.basic)} />
        {allowances.map(([k, v]) => <Row key={k} l={`Allowance — ${k}`} v={fmt(v)} />)}
        {Number(slip.no_pay_days) > 0 && (
          <Row l={`No-pay (${Number(slip.no_pay_days)} day${Number(slip.no_pay_days) === 1 ? '' : 's'})`} v={fmt(slip.no_pay_deduction)} neg />
        )}
        <Row l="Gross earnings" v={fmt(slip.gross)} strong />

        <p className="px-5 pt-5 pb-2 font-body text-xs tracking-widest3 text-brand uppercase">Deductions</p>
        <Row l="EPF — employee 8%" v={fmt(slip.epf_employee)} neg />
        <Row l="APIT" v={fmt(slip.apit)} neg />
        <Row l="Net pay" v={fmt(slip.net)} strong />

        <p className="px-5 pt-5 pb-2 font-body text-xs tracking-widest3 text-brand uppercase">Employer contributions (not deducted)</p>
        <Row l="EPF — employer 12%" v={fmt(slip.epf_employer)} />
        <Row l="ETF — employer 3%" v={fmt(slip.etf_employer)} />

        <footer className="px-6 py-4 font-body text-[11px] text-mute-3">
          Statutory rates per verified tenant reference data (docs/STATUTORY.md basis). Generated by the HR platform.
        </footer>
      </div>
      <p className="max-w-2xl mx-auto mt-4 font-body text-xs text-mute-3 print:hidden">
        Use your browser&apos;s Print (Ctrl+P) to save as PDF.
      </p>
    </main>
  );
}
