import { notFound } from 'next/navigation';
import { pgSsl } from '../../../lib/pg';
import postgres from 'postgres';
import { canUseModule } from '@hr/entitlements';
import { ENTITIES, runEntityQuery } from '../../../lib/entities';
import { getTenantContext } from '../../../lib/tenant';
import { PrintButton } from '../../../components/PrintButton';

export const dynamic = 'force-dynamic';

/**
 * Branded report for any registered entity — company logo, brand color and
 * name in the header; browser print → PDF. One template, every module.
 */
export default async function ReportPage(ctx0: { params: Promise<{ entity: string }> }) {
  const { entity } = await ctx0.params;
  const def = ENTITIES[entity];
  if (!def) notFound();
  const ctx = await getTenantContext();
  if (!ctx || !canUseModule(ctx.entitlements, def.moduleKey as never)) notFound();

  const db = postgres(ctx.dbUrl, { max: 1, onnotice: () => {}, ...pgSsl(ctx.dbUrl) });
  let rows: Record<string, unknown>[] = [];
  try {
    rows = await runEntityQuery(db, def);
  } finally {
    await db.end({ timeout: 2 });
  }
  const cols = rows.length ? Object.keys(rows[0]!) : [];
  const displayName = (ctx as { displayName?: string }).displayName ?? ctx.slug;
  const brand = ctx.theme?.colors?.['--brand'] ?? '#4F46E5';

  return (
    <main className="min-h-svh bg-ink" style={(ctx.theme?.colors ?? {}) as React.CSSProperties}>
      <div className="max-w-5xl mx-auto px-8 py-10">
        <header
          className="flex items-center gap-4 pb-5 mb-6 border-b-4"
          style={{ borderColor: brand }}
        >
          {ctx.theme?.logoUrl && (
            // eslint-disable-next-line @next/next/no-img-element
            <img src={ctx.theme.logoUrl} alt="" className="h-12 w-12 object-contain" />
          )}
          <div>
            <div className="text-xl font-bold text-chalk">{displayName}</div>
            <div className="text-sm text-mute-2">
              {def.label} · generated {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}
            </div>
          </div>
          <div className="ml-auto flex items-center gap-3">
            <span className="text-xs text-mute-3">{rows.length} rows</span>
            <PrintButton />
          </div>
        </header>

        {rows.length === 0 ? (
          <p className="text-sm text-mute-3">No data.</p>
        ) : (
          <table className="w-full text-xs">
            <thead>
              <tr className="text-left border-b-2 border-line">
                {cols.map((c) => (
                  <th key={c} className="py-2 pr-3 font-semibold text-mute-1 capitalize">
                    {c.replace(/_/g, ' ')}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rows.map((r, i) => (
                <tr key={i} className="border-b border-line">
                  {cols.map((c) => (
                    <td key={c} className="py-1.5 pr-3 text-chalk">
                      {r[c] == null ? '—' : String(r[c])}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        )}
        <footer className="mt-6 pt-3 border-t border-line text-[10px] text-mute-3">
          {displayName} · {def.label} · Confidential — generated by the HR platform
        </footer>
      </div>
    </main>
  );
}
